name: Run linters
on:
  push:
    branches:
    - main
  pull_request:
permissions:
  contents: read
jobs:
  lint:
    name: golangci-lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: 1.19
      - run: go mod download
      - uses: golangci/golangci-lint-action@v3.4.0
        with:
          skip-cache: true
          skip-pkg-cache: true
